# Generated by Django 6.0.4 on 2026-05-17 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], db_index=True, default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(db_index=True)),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], db_index=True, default='pending', max_length=15)),
                ('reason', models.TextField(blank=True, default='', help_text="Patient's stated reason for visit")),
                ('notes', models.TextField(blank=True, default='', help_text="Doctor's post-consultation notes (visible to doctor and admin only)")),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_30m_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Who cancelled this appointment (patient, doctor, or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
                ('rescheduled_from', models.ForeignKey(blank=True, help_text='Points to the original appointment this one replaced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='base.appointment')),
                ('slot', models.OneToOneField(blank=True, help_text='Set to NULL on cancellation so the slot can be re-used. The appointment record itself is kept for audit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='base.timeslot')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Clinic start time, e.g. 08:00')),
                ('end_time', models.TimeField(help_text='Clinic end time, e.g. 17:00')),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=15, help_text='Duration of each bookable slot in minutes')),
                ('max_patients_per_day', models.PositiveSmallIntegerField(default=20, help_text='Hard cap on daily appointments (FR-7.2)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'ordering': ['doctor', 'day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['doctor', 'date', 'status'], name='base_timesl_doctor__1378db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='base_appoin_patient_01d7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date', 'status'], name='base_appoin_doctor__c93b44_idx'),
        ),
    ]
