# Generated by Django 6.0.4 on 2026-05-19 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_timeslot_appointment_doctorschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], db_index=True, default='active', max_length=10)),
                ('current_position', models.PositiveSmallIntegerField(default=0, help_text='Queue number currently being served (0 = none called yet)')),
                ('next_number', models.PositiveSmallIntegerField(default=1, help_text='Next queue number to assign')),
                ('pause_reason', models.CharField(blank=True, default='', max_length=300)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('total_pause_minutes', models.PositiveSmallIntegerField(default=0, help_text='Cumulative minutes the queue was paused today (FR-3.7)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='queue_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Queue Session',
                'verbose_name_plural': 'Queue Sessions',
                'ordering': ['-date', 'doctor'],
            },
        ),
        migrations.CreateModel(
            name='QueuePauseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.DateTimeField()),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pause_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_logs', to='base.queuesession')),
            ],
            options={
                'verbose_name': 'Queue Pause Log',
                'verbose_name_plural': 'Queue Pause Logs',
                'ordering': ['-paused_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveSmallIntegerField(help_text="Patient's immutable ticket number for this session")),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called — please proceed to room'), ('in_consult', 'In Consultation'), ('completed', 'Completed'), ('skipped', 'Skipped / No-Show'), ('left', 'Left Queue Voluntarily')], db_index=True, default='waiting', max_length=12)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notified_2away', models.BooleanField(default=False, help_text="True once the '2 positions away' push notification has been sent")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='base.appointment')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='base.queuesession')),
            ],
            options={
                'verbose_name': 'Queue Entry',
                'verbose_name_plural': 'Queue Entries',
                'ordering': ['queue_number'],
            },
        ),
        migrations.AddIndex(
            model_name='queuesession',
            index=models.Index(fields=['date', 'status'], name='base_queues_date_35307c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queuesession',
            unique_together={('doctor', 'date')},
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['session', 'status'], name='base_queuee_session_1ff266_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['patient', 'status'], name='base_queuee_patient_3b3c89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queueentry',
            unique_together={('session', 'queue_number')},
        ),
    ]
