# Generated by Django 6.0.4 on 2026-05-25 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_queuesession_queuepauselog_queueentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_type', models.CharField(choices=[('admin', 'Hospital Admin'), ('ambulance', 'Ambulance Dispatch'), ('duty_doctor', 'Duty Doctor'), ('emergency_line', 'Emergency Hotline')], db_index=True, default='admin', max_length=20)),
                ('phone_number', models.CharField(help_text='E.164 format e.g. +233301234567', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='WhatsApp number if different from phone', max_length=20)),
                ('fcm_token', models.TextField(blank=True, default='', help_text='Firebase Cloud Messaging device token for push alerts')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['contact_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude from device GPS', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude from device GPS', max_digits=10, null=True)),
                ('gps_accuracy_meters', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in metres reported by device', max_digits=8, null=True)),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('ambulance', 'Ambulance Request'), ('cardiac', 'Cardiac / Chest Pain'), ('accident', 'Accident / Trauma'), ('maternity', 'Maternity Emergency'), ('other', 'Other')], db_index=True, default='medical', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Optional patient description of the emergency')),
                ('status', models.CharField(choices=[('pending', 'Pending — Awaiting Response'), ('dispatched', 'Dispatched — Help On the Way'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled by Patient'), ('false_alarm', 'False Alarm')], db_index=True, default='pending', max_length=15)),
                ('confirmed_at', models.DateTimeField(help_text='When patient confirmed SOS (after 5-second countdown, FR-5.2)')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_seconds', models.PositiveIntegerField(blank=True, help_text='Seconds between SOS confirmation and dispatch', null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('ambulance_plate', models.CharField(blank=True, default='', max_length=20)),
                ('ambulance_eta_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Estimated ambulance arrival in minutes, set on dispatch', null=True)),
                ('admin_notified', models.BooleanField(default=False)),
                ('patient_ack_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, help_text='Admin or doctor who updated the status to dispatched/resolved', limit_choices_to={'role__in': ['admin', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_emergencies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Request',
                'verbose_name_plural': 'Emergency Requests',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pending — Awaiting Response'), ('dispatched', 'Dispatched — Help On the Way'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled by Patient'), ('false_alarm', 'False Alarm')], max_length=15)),
                ('new_status', models.CharField(choices=[('pending', 'Pending — Awaiting Response'), ('dispatched', 'Dispatched — Help On the Way'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled by Patient'), ('false_alarm', 'False Alarm')], max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='base.emergencyrequest')),
            ],
            options={
                'verbose_name': 'Emergency Status Log',
                'verbose_name_plural': 'Emergency Status Logs',
                'ordering': ['created_at'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['patient', 'status'], name='base_emerge_patient_8ed755_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['status', 'confirmed_at'], name='base_emerge_status_708cfb_idx'),
        ),
    ]
