# Generated by Django 6.0.4 on 2026-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_doctorschedule_active_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='code',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='prefix',
            field=models.CharField(blank=True, default='', help_text='Hubtel OTP prefix', max_length=20),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='request_id',
            field=models.CharField(blank=True, default='', help_text='Hubtel OTP request ID', max_length=100),
        ),
    ]
