# Generated by Django 6.0.4 on 2026-07-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_hubtel_otp_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='request_id',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='code',
            field=models.CharField(default=0, help_text='Plaintext 6-digit OTP code', max_length=6),
            preserve_default=False,
        ),
    ]
