# Generated by Django 6.0.4 on 2026-09-08 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_otpverification_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('lockout', 'Account Lockout'), ('register', 'Registration'), ('password_reset', 'Password Reset'), ('role_change', 'Role Change'), ('profile_update', 'Profile Update'), ('user_deleted', 'User Deleted'), ('booking', 'Appointment Booked'), ('cancellation', 'Appointment Cancelled'), ('emergency', 'Emergency SOS')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('appointment', 'Appointment'), ('queue', 'Queue'), ('emergency', 'Emergency'), ('message', 'Message'), ('reminder', 'Reminder')], default='appointment', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='base_notifi_recipie_f4002f_idx'), models.Index(fields=['recipient', '-created_at'], name='base_notifi_recipie_43fdd4_idx')],
            },
        ),
    ]
