# Generated by Django 6.0.4 on 2026-09-09 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_auditlog_event_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_by_reception',
            field=models.BooleanField(default=False, help_text='True if this appointment was booked by receptionist/admin via phone call'),
        ),
        migrations.CreateModel(
            name='DoctorAvailabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('override_type', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=15)),
                ('start_time', models.TimeField(blank=True, help_text='Optional custom start time for this date (uses schedule default if blank)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Optional custom end time for this date (uses schedule default if blank)', null=True)),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=15, help_text='Slot duration for this date override')),
                ('max_patients_per_day', models.PositiveSmallIntegerField(default=20, help_text='Max patients for this date override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Availability Override',
                'verbose_name_plural': 'Doctor Availability Overrides',
                'ordering': ['doctor', 'date'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date'), name='unique_doctor_date_override')],
            },
        ),
    ]
